### ISSUE TITLE
Vartrix error, but only in one of several batches

### ISSUE THREAD

**Issue by zhangbw3187** [wheaton5/souporcell#100]
Hi, dear wheaton5,

I've met an vartrix error when trying to demultiplex one of my scRNA-seq batches, with following commands:
'./souporcell_pipeline.py -i $POS_BAM -b $BARCODES -f $REF_FAS -t $NUM_THREADS -o $OUT_DIR -k $NUM_CLUSTERS'
(variables direct to different batches) 
I suppose the commands are fine, because same code went smoothly for 7 out of 8 batches.

However, in one batch, I got:

`imports done
checking bam for expected tags
checking fasta
generating fastqs with cell barcodes and umis in readname
remapping with minimap2
cleaning up tmp fastqs
repopulating cell barcode and UMI tags
False
False
retag.py --sam /vol/projects...
sorting retagged bam files
merging sorted bams
cleaning up tmp samfiles
running freebayes
merging vcfs
running vartrix
Traceback (most recent call last):
  File "./souporcell_pipeline.py", line 560, in <module>
    vartrix(args, final_vcf, bam)
  File "./souporcell_pipeline.py", line 483, in vartrix
    subprocess.check_call(cmd, stdout = out, stderr = err)
  File "/home/bzhang/package/miniconda3/envs/souporcell/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vartrix', '--mapq', '30', '-b', '/vol/projects...' ... ]' returned non-zero exit status 101.
`

The output from other batches look like this:
`imports done
checking bam for expected tags
checking fasta
generating fastqs with cell barcodes and umis in readname
remapping with minimap2
cleaning up tmp fastqs
repopulating cell barcode and UMI tags
False
False
retag.py --sam /vol/projects...
sorting retagged bam files
merging sorted bams
cleaning up tmp samfiles
running freebayes
merging vcfs
running vartrix
running souporcell clustering
/vol/proje...
running souporcell doublet detection
running co inference of ambient RNA and cluster genotypes
done`

I also checked the errors from vartrix, The crash appears to be caused by an invalid CIGAR string in the BAM file.
The failure is due to one of these 3 reasons:
"'deletion' (D) found before any operation describing read sequence"
"'reference skip' (N) found before any operation describing read sequence"
"'hard clip' (H) found in between operations, contradicting SAMv1 spec that hard clips can only be at the ends of reads"
So there may be a bug in whichever tool is generating the BAM file that's being passed to vartrix. 

But I'm not sure how to solve this.

Can you help me to look at this?

Thanks a lot,
Bowen

**Comment by zhangbw3187** [comment]
I also tried to re-align with cellranger v4.0 or v5.0 to generate bam files before running souporcell.

But errors stay the same...
