### ISSUE TITLE
File not found error for souporcell/souporcell/target/release/souporcell

### ISSUE THREAD

**Issue by Zethson** [wheaton5/souporcell#102]
Hi,

I am running souporcell as follows:

`singularity exec -H /mnt/platte_1 souporcell.sif souporcell/souporcell_pipeline.py -i merged.bam -b barcodes.tsv -f hg38.fasta -t 8 -o souporcelloutput -k 4q'
`

which results in:

```
running souporcell clustering
/mnt/platte_1/mdsc_ipf_ISIS/souporcell/souporcell/target/release/souporcell -k 4 -a souporcelloutput/alt.mtx -r souporcelloutput/ref.mtx --restarts 100 -b barcodes.tsv --min_ref 10 --min_alt 10 --threads 8
Traceback (most recent call last):
  File "/mnt/platte_1/mdsc_ipf_ISIS/souporcell/souporcell_pipeline.py", line 593, in <module>
    souporcell(args, ref_mtx, alt_mtx, final_vcf)
  File "/mnt/platte_1/mdsc_ipf_ISIS/souporcell/souporcell_pipeline.py", line 531, in souporcell
    subprocess.check_call(cmd, stdout = log, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/platte_1/mdsc_ipf_ISIS/souporcell/souporcell/target/release/souporcell': '/mnt/platte_1/mdsc_ipf_ISIS/souporcell/souporcell/target/release/souporcell'
```

Do you have any idea?

**Comment by Zethson** [comment]
Oops, `souporcell_pipeline.py` is a global executable inside the container and not related to the code
