### ISSUE TITLE
Pipeline error - samtools merge after the RETAG step

### ISSUE THREAD

**Issue by jakalssj3** [wheaton5/souporcell#104]
Hello. I'm analyzing my 10x scRNA-seq data with sopourcell pipeline under singularity and the pipeline stops at the retag step. There seems to be a problem with the samtools merge command. I put the content of stdout below:

``` bash
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory soupourcell_out-k8
repopulating cell barcode and UMI tags
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_0.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_0.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_1.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_1.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_2.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_2.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_3.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_3.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_4.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_4.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_5.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_5.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_6.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_6.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_7.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_7.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_8.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_8.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_9.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_9.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_10.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_10.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_11.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_11.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_12.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_12.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_13.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_13.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_14.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_14.bam
False
False
retag.py --sam soupourcell_out-k8/souporcell_minimap_tmp_15.sam --no_umi False --umi_tag UB --cell_tag CB --out soupourcell_out-k8/souporcell_retag_tmp_15.bam
sorting retagged bam files
merging sorted bams
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 578, in <module>
    retag(args, minimap_tmp_files)
  File "/opt/souporcell/souporcell_pipeline.py", line 332, in retag
    subprocess.check_call(["samtools", "merge", final_bam] + filenames)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['samtools', 'merge', 'soupourcell_out-k8/souporcell_minimap_tagged_sorted.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_0.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_1.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_2.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_3.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_4.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_5.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_6.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_7.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_8.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_9.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_10.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_11.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_12.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_13.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_14.bam', 'soupourcell_out-k8/souporcell_retag_sorted_tmp_15.bam']' returned non-zero exit status 1.
```

I tried doing the merge step manually and there is a difference in the size of the file (13GB vs 21GB after manual merge) so this step never completes. I also tried restarting the pipeline after replacing the merged bam file with the one I created manually, but the pipeline does not recognize it.

**Comment by jakalssj3** [comment]
Just in case, below is the content of the "retag.err" file

``` bash
cat retag.err
[bam_sort_core] merging from 8 files and 1 in-memory blocks...
[bam_sort_core] merging from 8 files and 1 in-memory blocks...
[bam_sort_core] merging from 10 files and 1 in-memory blocks...
[bam_sort_core] merging from 11 files and 1 in-memory blocks...
[bam_sort_core] merging from 9 files and 1 in-memory blocks...
[bam_sort_core] merging from 11 files and 1 in-memory blocks...
[bam_sort_core] merging from 11 files and 1 in-memory blocks...
[bam_sort_core] merging from 11 files and 1 in-memory blocks...
[bam_sort_core] merging from 13 files and 1 in-memory blocks...
[bam_sort_core] merging from 14 files and 1 in-memory blocks...
[bam_sort_core] merging from 18 files and 1 in-memory blocks...
[bam_sort_core] merging from 17 files and 1 in-memory blocks...
[bam_sort_core] merging from 21 files and 1 in-memory blocks...
[bam_sort_core] merging from 21 files and 1 in-memory blocks...
[bam_sort_core] merging from 24 files and 1 in-memory blocks...
[bam_sort_core] merging from 23 files and 1 in-memory blocks...
```

**Comment by sbaghai** [comment]
Hello @wheaton5, I am expericencing the same issue as  @jakalssj3, could it be related to the available RAM? Many thanks ahead!

**Comment by domenico-somma** [comment]
Hi there,
I have the same issue with the example data provided on main page, not sure where is the problem (I got 120 Gb Ram available on the server, so I doubt there is an issue with the RAM amount)

**Comment by HibaLaghrissi** [comment]
Hi there,
did someone manage to find the solution ?

**Comment by wheaton5** [comment]
Hi, sorry for abandoning this for some time. I will put some effort into fixing this tho I have never encountered it myself. If someone could put together a minimal example and send it to me that would be very useful. samtools merge should have spit something out on stderr, not to retag.err as I didn't pipe the stderr of that subprocess call to retag.err although I should have. I should start with that fix. But it would really be helpful to have a minimal example for debugging if anyone can provide that.

**Comment by Boroviak-Lab** [comment]
Hitting a similar error now. Allocated about 60GB RAM, so don't think its the issue. Happy to help trying to figure out a cause or workaround if anyone has any ideas or suggestions.

**Comment by meliamne** [comment]
Ran into this issue while running a bunch of libraries. Re-running cellranger fixed the issue in my case.

**Comment by NewtontheNeuron** [comment]
Hi everyone, I am also experiencing a similar issue. I used souporcell several times with one dataset. However, I am only seeing this error on a new dataset with different but similar experimental protocols.

@wheaton5 were you able to get a minimal example?
I won't be able to share my data. But, I am open to helping with debugging wherever I can, God willing. I suspect that it would be hard to develop a minimal example with publicly available data since we don't know what we are trying to replicate yet (to my understanding). Could you walk me through your debug process. Perhaps I can try to debug on my end by running selective parts at a time in order to identify what the code is doing to yield this error.

I opened a new issue for my specific run. #259
