### ISSUE TITLE
error debug help

### ISSUE THREAD

**Issue by maxozo** [wheaton5/souporcell#124]
Hi, running souporcell i get the following error:
```
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 596, in <module>
    doublets(args, ref_mtx, alt_mtx, cluster_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 541, in doublets
    subprocess.check_call([directory+"/troublet/target/release/troublet", "--alts", alt_mtx, "--refs", ref_mtx, "--clusters", cluster_file], stdout = dub, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/souporcell/troublet/target/release/troublet', '--alts', '6123STDY10205670/alt.mtx', '--refs', '6123STDY10205670/ref.mtx', '--clusters', '6123STDY10205670/clusters_tmp.tsv']' returned non-zero exit status 101.
```
Any idea whats causing this?

**Comment by GenOnyx** [comment]
Hi,
I am getting the same error. The input command I have used is:
_python souporcell_pipeline.py -i A.merged.bam -b GSM2560245_barcodes.tsv -f genome.fa -t 32 -o CPT204c -k 6 --known_genotypes 21_00204.vcf_

Is there any specific input format required that I am missing?
@maxozo were you able to fix the issue?

**Comment by timslittle** [comment]
This is quite old now but in case it is possibly helpful at all some solutions are suggested here: [Issue#128](https://github.com/wheaton5/souporcell/issues/128). I also encountered this problem and the issue was that I was re-starting a failed pipeline and needed to delete the old `.done` files.
