### ISSUE TITLE
Error running with --known_genotypes

### ISSUE THREAD

**Issue by cdelacalle** [wheaton5/souporcell#132]
Thanks for this super helpful tool!

I was able to demultiplex my samples but now I additionally have VCF files derived from SNP microarrays.
So I am running the app with --known_genotypes and --known_genotypes_sample_names. 
The VCF has 19 samples in it although I am just using 4 in one particular reaction.

Somethink like this:

`--known_genotypes /path/merged.vcf --known_genotypes_sample_names 4_ES97 1_ES70 3_ES43 16_ES16 -k 4`

However I get an error, I think it is related to the VCF file format:

```
sorting retagged bam files
merging sorted bams
cleaning up tmp samfiles
using known genotypes
***** WARNING: File /demultiplexed_4_known_genotypes/depth_merged.bed has inconsistent naming convention for record:
KI270728.1	183748	183810

Error: Invalid record in file /path/merged_n19.vcf. Record is 
0	0	1:145030589	G	.	.	.	PR	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0
```
Since I am not familiar with VCF files, I though of asking you: do you see what can be the problem?
Thanks in advance!

Best regards.
Carlos

P.S: Just in case i leave the rest of the script...:
```
singularity exec --bind /disco1/onedrive /home/cdelacalle/souporcell_latest.sif souporcell_pipeline.py \
	-i /disco1/onedrive/Project_Rheum_SC/souporcell/reaction1_multiome/gex_possorted_bam.bam \
	-b /disco1/onedrive/Project_Rheum_SC/souporcell/reaction1_multiome/reac1_gem_human.csv \
	-f /disco1/onedrive/Project_Rheum_SC/scrna/transcriptome_references/cellranger_arc/refdata-cellranger-arc-GRCh38-2020-A-2.0.0/fasta/genome.fa \
	-t 12 \
	-o /disco1/onedrive/Project_Rheum_SC/souporcell/reaction1_multiome/demultiplexed_4_known_genotypes \
	--known_genotypes /disco1/onedrive/Project_Rheum_SC/DNA_genomic/2020-219-ILL_GSAGRA_N=19/GSP_2020-219-ILL_GSAGRA_N=19/PLINK_241121_0908/merged_n19.vcf \
	--known_genotypes_sample_names 4_ES97GSAGRAD105082 1_ES70GSAGRAD105083 3_ES43GSAGRAD105084 16_ES16GSAGRAD105085 \
	-k 4
```

**Comment by cdelacalle** [comment]
Indeed: this is the `grep '#CHROM' vcf_filename`

`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1_ES70GSAGRAD105083	2_ES86GSAGRAD105086	3_ES43GSAGRAD105084	4_ES97GSAGRAD105082	5_ES59GSAGRAD105087	6_ES75GSAGRAD1050907_ES80GSAGRAD105097	8_ES32GSAGRAD105088	9_ES53GSAGRAD105098	10_ES21GSAGRAD105092	11_ES26GSAGRAD105099	12_ES64GSAGRAD105094	13_ES96GSAGRAD105100	14_ES48GSAGRAD105091	15_ES37GSAGRAD105095	16_ES16GSAGRAD105085	17_ES10GSAGRAD105096	18_ES05GSAGRAD105089	19_ES91GSAGRAD105093`

... and these are the first two lines of the VCF file, after the #CHROM line:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1_ES70GSAGRAD105083	2_ES86GSAGRAD105086	3_ES43GSAGRAD105084	4_ES97GSAGRAD105082	5_ES59GSAGRAD105087	6_ES75GSAGRAD105090	7_ES80GSAGRAD105097	8_ES32GSAGRAD105088	9_ES53GSAGRAD105098	10_ES21GSAGRAD105092	11_ES26GSAGRAD105099	12_ES64GSAGRAD105094	13_ES96GSAGRAD105100	14_ES48GSAGRAD105091	15_ES37GSAGRAD105095	16_ES16GSAGRAD105085	17_ES10GSAGRAD105096	18_ES05GSAGRAD105089	19_ES91GSAGRAD105093
0	0	1:145030589	G	.	.	.	PR	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0
0	0	10:86919364	I	.	.	.	PR	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0	0/0
```

**Comment by changostraw** [comment]
I am also getting this error: 

Error: Invalid record in file header_cecum_subset.vcf. Record is 
chr1	777664	1:713044:C:<CN2>:755966	C	<CN2>	.	PASS	AC=0;AN=4	GT	0/0	0/0

I have used this same vcf for other tools (Demuxlet, vireo) without a problem and used a similar file before with souporcell without a problem. The only difference with this file is that this is imputed genotype data, not raw genotype data. 
Any idea why it isn't liking this chr1 row? thanks!

**Comment by changostraw** [comment]
here is the columns headers:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	366_GT15314	400_GT14352

**Comment by wheaton5** [comment]
In the format field you have two colons back yo back. There needs to be a dot between them to indicate no value. Not sure which package im using that is complaining, but i think that is technically an invalid record due to that bit

**Comment by wheaton5** [comment]
Oh wait, nvm. That is in the id field

**Comment by wheaton5** [comment]
But also why have a field with an empty alt

**Comment by wheaton5** [comment]
Can u see which stage is failing and give me any more error output?

**Comment by changostraw** [comment]
It fails during calling candidate variants/freebayes just after creating this file: common_variants_covered_tmp.vcf

Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 586, in <module>
    final_vcf = freebayes(args, bam, fasta)
  File "/opt/souporcell/souporcell_pipeline.py", line 398, in freebayes
    subprocess.check_call(["bedtools", "intersect", "-wa", "-a", args.common_variants, "-b", args.out_dir + "/depth_merged.bed"], stdout = vcf)
  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bedtools', 'intersect', '-wa', '-a', '/project/rrg-gturecki/Sarah/donorGT/imputed/header_cecum_subset.vcf', '-b', '/project/rrg-gturecki/Sarah/Demuxafy/Soupercell/cecum_poolA_imputed/depth_merged.bed']' returned non-zero exit status 1.

**Comment by wheaton5** [comment]
Looks like bedtools has a problem with it. I'd just try removing all variants with a missing ALT allele.

**Comment by maxim-h** [comment]
@wheaton5 
I'm having a similar issue. In my case I have microarray genotyping data that for stupid reasons had to be exported to PLINK and later to VCF. This little maneuver ended up costing us information about the ALT allele in cases where all samples have a reference genotype. 
Also in the records that others are complaining above I see that all genotypes are 0/0.

That being said it seems like these types of variants wouldn't be too useful with regards to clustering the genotypes. But would they potentially be useful in filtering out some false positive calls from the `cluster_genotypes,vcf`? Or can we just ignore those?
