### ISSUE TITLE
merging issues

### ISSUE THREAD

**Issue by HibaLaghrissi** [wheaton5/souporcell#135]
Hi,

I am using souporcell for multiple data and it worked quiet well, but now it's having some issues even if I didn't change anything in my scripts... I even tried it with the data it used to work on, but I have the same error popping out : 

Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 584, in <module>
    final_vcf = freebayes(args, bam, fasta)
  File "/opt/souporcell/souporcell_pipeline.py", line 465, in freebayes
    subprocess.check_call(["ls "+args.out_dir+'/*.vcf | xargs -n1 -P'+str(args.threads)+' bgzip'],shell=True)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ls outs_17042022/nose/*.vcf | xargs -n1 -P15 bgzip']' returned non-zero exit status 123.
WARNING: do not run this command twice on the same file, otherwise then you need to remove duplicted lines

I have freebayes files but it fails to merge them...

This is how I run souporcell : 
singularity exec -B ~/Workspace $souporcell souporcell_pipeline.py -i ../data_nose/${S}.bam -b ../data_nose/${S}.barcodes -f $genome --threads $CPU -o $O/$S -k $n

Thank you

**Comment by wheaton5** [comment]
If its not working on data it used to work on, its probably not a souporcell issue. Make sure you arent up against your disk quota on your cluster or something like that. You can try manually merging to see if that works. Not sure what to say.

**Comment by HibaLaghrissi** [comment]
Thank you for your quick response 

I have enough space to run it and I tried it on my work computer, personal computer and on my work server… the strange thing is that I have the same issue each time 

I deleted Souporcell and re-installed it again but still the same issue (with old data too) 

i don’t have bcftools errors or anything special

**Comment by HibaLaghrissi** [comment]
Just to add more details :
![Capture d’écran du 2022-04-18 15-38-58](https://user-images.githubusercontent.com/97699142/163816178-97502496-16b7-4160-b19e-f1efacb7c7a1.png)
 I have those files as souporcell input, the .err files have a sentence printed, for example :
freebayes -f ../genome.fa -iXu -C 2 -q 20 -n 3 -E 1 -m 30 --min-coverage 20 --pooled-continuous --skip-coverage 100000 -r chrX:15105243-156040895 outs_17042022/nose/souporcell_minimap_tagged_sorted.bam

**Comment by aaaaaaaaaayong** [comment]
I encountered the same problem. Have you solved it?
