### ISSUE TITLE
Doublet detection. Returned non-zero exit status 101

### ISSUE THREAD

**Issue by MrLocuace** [wheaton5/souporcell#175]
Hi !
I am running this script in a HPC:

#!/bin/bash
module load apptainer/1.1.4

SOUPORCELL_DIR=/mypath/test
BATCH=${1}
SAMPLE=$(echo "$BATCH" | cut -d"_" -f1)

REF_DIR=/tmp/souporcell/references

#gunzip ${BARCODES_DIR}/barcodes.tsv.gz

apptainer exec --bind $SOUPORCELL_DIR:/tmp souporcell_latest.sif souporcell_pipeline.py \
				-i /tmp/fastqs/${SAMPLE}_OUT/outs/possorted_genome_bam.bam \
				-b /tmp/fastqs/${SAMPLE}_OUT/outs/filtered_feature_bc_matrix/barcodes.tsv \
				-f ${REF_DIR}/refdata-gex-GRCh38-2020-A/fasta/genome.fa \
				--common_variants ${REF_DIR}/common_variants_grch38.vcf \
				--skip_remap SKIP_REMAP \
				-t 16 \
				-o /tmp/skip_remap_OUTS/${SAMPLE}_souporcell \
				-k 3

But I get the error "returned non-zero exit status 101" at the doublet detection step:

[me@midway3-login3 scripts]$ bash souporcell_skipRemap_k_3.sh B6-c1-10X
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory /tmp/skip_remap_OUTS/B6-c1-10X_souporcell
using common variants
16
***** WARNING: File /tmp/skip_remap_OUTS/B6-c1-10X_souporcell/depth_merged.bed has inconsistent naming convention for record:
KI270727.1	8904	8942

***** WARNING: File /tmp/skip_remap_OUTS/B6-c1-10X_souporcell/depth_merged.bed has inconsistent naming convention for record:
KI270727.1	8904	8942

running vartrix
running souporcell clustering
/opt/souporcell/souporcell/target/release/souporcell -k 3 -a /tmp/skip_remap_OUTS/B6-c1-10X_souporcell/alt.mtx -r /tmp/skip_remap_OUTS/B6-c1-10X_souporcell/ref.mtx --restarts 100 -b /tmp/fastqs/B6-c1-10X_OUT/outs/filtered_feature_bc_matrix/barcodes.tsv --min_ref 10 --min_alt 10 --threads 16
running souporcell doublet detection
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 596, in <module>
    doublets(args, ref_mtx, alt_mtx, cluster_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 541, in doublets
    subprocess.check_call([directory+"/troublet/target/release/troublet", "--alts", alt_mtx, "--refs", ref_mtx, "--clusters", cluster_file], stdout = dub, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/souporcell/troublet/target/release/troublet', '--alts', '/tmp/skip_remap_OUTS/B6-c1-10X_souporcell/alt.mtx', '--refs', '/tmp/skip_remap_OUTS/B6-c1-10X_souporcell/ref.mtx', '--clusters', '/tmp/skip_remap_OUTS/B6-c1-10X_souporcell/clusters_tmp.tsv']' returned non-zero exit status 101.

The error file shows a similar text

Could you please help me?
Thank you !

**Comment by rdf1993** [comment]
I also meet this problem. Have you solved it yet?

**Comment by wheaton5** [comment]
This generally happens when there are no variants that pass filters. But usually just no variants for some silly reason like inconsistent chromosome naming or similar.

**Comment by rdf1993** [comment]
I can see variants in souporcell_merged_sorted_vcf.vcf.gz files as:
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	unknown
chr1	14653	.	C	T	0.0216654	.	AB=0.227273;ABP=17.2236;AC=1;AF=0.5;AN=2;AO=5;CIGAR=1X;DP=22;DPB=22;DPRA=0;EPP=13.8677;EPPR=13.3567;GTI=0;LEN=1;MEANALT=1;MQM=33.4;MQMR=42.5882;NS=1;NUMALT=1;ODDS=5.2981;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=160;QR=593;RO=17;RPL=0;RPP=13.8677;RPPR=13.3567;RPR=5;RUN=1;SAF=5;SAP=13.8677;SAR=0;SRF=17;SRP=39.9253;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0/1:22:17,5:17:593:5:160:-6.41666,0,-44.1812
chr1	14677	.	G	A	5.63563e-08	.	AB=0.111111;ABP=38.4777;AC=1;AF=0.5;AN=2;AO=3;CIGAR=1X;DP=27;DPB=27;DPRA=0;EPP=9.52472;EPPR=4.45795;GTI=0;LEN=1;MEANALT=1;MQM=43.6667;MQMR=41.8333;NS=1;NUMALT=1;ODDS=18.1601;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=111;QR=876;RO=24;RPL=0;RPP=9.52472;RPPR=4.45795;RPR=3;RUN=1;SAF=3;SAP=9.52472;SAR=0;SRF=24;SRP=55.1256;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0/1:27:24,3:24:876:3:111:-1.48411,0,-65.4728
chr1	126113	.	C	A	727.721	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=25;CIGAR=1X;DP=25;DPB=25;DPRA=0;EPP=3.09716;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=57.12;MQMR=0;NS=1;NUMALT=1;ODDS=39.2625;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=913;QR=0;RO=0;RPL=13;RPP=3.09716;RPPR=0;RPR=12;RUN=1;SAF=25;SAP=57.2971;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1/1:25:0,25:0:0:25:913:-81.9173,-7.52575,0
chr1	128613	.	A	G	0	.	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=5;CIGAR=1X;DP=91;DPB=91;DPRA=0;EPP=13.8677;EPPR=148.022;GTI=0;LEN=1;MEANALT=3;MQM=44;MQMR=58.4756;NS=1;NUMALT=1;ODDS=81.5499;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=185;QR=2962;RO=82;RPL=0;RPP=13.8677;RPPR=140.29;RPR=5;RUN=1;SAF=5;SAP=13.8677;SAR=0;SRF=79;SRP=155.967;SRR=3;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL0/0:91:82,5:82:2962:5:185:0,-10.2792,-250.037
chr1	128798	.	C	T	787.977	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=32;CIGAR=1X;DP=32;DPB=32;DPRA=0;EPP=64.083;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=53.6562;MQMR=0;NS=1;NUMALT=1;ODDS=48.9666;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1184;QR=0;RO=0;RPL=32;RPP=72.4974;RPPR=0;RPR=0;RUN=1;SAF=31;SAP=64.083;SAR=1;SRF=0;SRP=0;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1/1:32:0,32:0:0:32:1184:-104.686,-9.63296,0
chr1	137923	.	C	T	0.000634436	.	AB=0.15;ABP=24.2907;AC=1;AF=0.5;AN=2;AO=3;CIGAR=1X;DP=20;DPB=20;DPRA=0;EPP=3.73412;EPPR=13.3567;GTI=0;LEN=1;MEANALT=1;MQM=40;MQMR=37.2941;NS=1;NUMALT=1;ODDS=8.83125;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=111;QR=629;RO=17;RPL=1;RPP=3.73412;RPPR=13.3567;RPR=2;RUN=1;SAF=3;SAP=9.52472;SAR=0;SRF=17;SRP=39.9253;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0/1:20:17,3:17:629:3:111:-2.88336,0,-44.311
chr1	150485	.	A	T	240.563	.	AB=0.357143;ABP=12.937;AC=1;AF=0.5;AN=2;AO=20;CIGAR=1X;DP=56;DPB=56;DPRA=0;EPP=46.4397;EPPR=76.8404;GTI=0;LEN=1;MEANALT=2;MQM=54.8;MQMR=49.6765;NS=1;NUMALT=1;ODDS=55.3917;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=692;QR=1234;RO=34;RPL=0;RPP=46.4397;RPPR=76.8404;RPR=20;RUN=1;SAF=20;SAP=46.4397;SAR=0;SRF=34;SRP=76.8404;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0/1:56:34,20:34:1234:20:692:-45.8667,0,-90.289
chr1	150490	.	T	C,G	0.000407739	.	AB=0.15,0.0666667;ABP=66.8516,100.871;AC=1,0;AF=0.5,0;AN=2;AO=9,4;CIGAR=1X,1X;DP=60;DPB=60;DPRA=0,0;EPP=22.5536,11.6962;EPPR=105.07;GTI=0;LEN=1,1;MEANALT=2,2;MQM=55.8889,55;MQMR=51.5106;NS=1;NUMALT=2;ODDS=9.27339;PAIRED=0,0;PAIREDR=0;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=333,136;QR=1727;RO=47;RPL=0,0;RPP=22.5536,11.6962;RPPR=105.07;RPR=9,4;RUN=1,1;SAF=9,4;SAP=22.5536,11.6962;SAR=0,0;SRF=47;SRP=105.07;SRR=0;TYPE=snp,snpGT:DP:AD:RO:QR:AO:QA:GL	0/1:60:47,9,4:47:1727:9,4:333,136:-13.0787,0,-134.015,-16.2277,-125.717,-151.721
chr1	150586	.	T	C	7.71486e-15	.	AB=0;ABP=0;AC=0;AF=0;AN=2;AO=16;CIGAR=1X;DP=203;DPB=203;DPRA=0;EPP=3.55317;EPPR=14.1696;GTI=0;LEN=1;MEANALT=1;MQM=58.75;MQMR=58.0481;NS=1;NUMALT=1;ODDS=125.992;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=580;QR=6703;RO=187;RPL=7;RPP=3.55317;RPPR=11.4756;RPR=9;RUN=1;SAF=16;SAP=37.7539;SAR=0;SRF=183;SRP=375.075;SRR=4;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0/0:203:187,16:187:6703:16:580:0,-8.61172,-549.722
......


But the matrix files are all empty after running vartrix:

alt.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
2032832 10241 0

ref.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
2032832 10241 0

**Comment by PeggySze** [comment]
I also meet this problem when applying souporcell to demultiplexing scATAC-seq data. Do anyone have ideas how to solve it ? Here is my alt.mtx and ref.mtx :
alt.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
62437 3995 0

ref.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
62437 3995 0

**Comment by CarlottaHS** [comment]
Running into the same issue. Has someone found a solution?
My alt.mtx and ref.mtx are however not empty. The first few lines look like that:

ref.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
217678 2527428 10169037
2 1623153 1
3 1492924 1

alt.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
217678 2527428 10169037
2 1623153 0
3 1492924 0

**Comment by wheaton5** [comment]
So you have 200k cells? Or are you using the unfiltered barcodes tsv? The barcodes should only be cell barcodes. Let me know if that is the issue or there are other problems.

**Comment by CarlottaHS** [comment]
Thanks for the quick reply!
You are right I am using the unfiltered barcodes. My issue is I am using the results of the cellranger multi pipeline as CellPlex was used for tagging each donor with a different barcode. My plan is to use the SNP analysis to confirm the CellPlex protocol has worked. I also read in a different issue on here that I should only use the filtered barcodes (#128 ). So what I did now was combine all the barcodes from the already into donors splitted and filtered dataset. However, I only have the combined unassigned bam file, which of course threw a warning that not many barcodes are matching, which I ignored for testing purposes as I thought that might just introduce more noise to the analysis. The same doublet error occured, but now my ref.mtx and alt.mtx are empty as well.

ref.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
0 12770 0

alt.mtx
%%MatrixMarket matrix coordinate real general
% written by sprs
0 12770 0

I also now ran it once only with the bam file and barcodes of one sample and not the pooled samples. This seems to be working, but have to do additional analysis there. 

But any idea what the best way to test the 10X multi output files is as the bam files are not filtered for the pooled samples? 

Thanks so much in advance!

**Comment by carmensandoval** [comment]
Hello,

I'm encountering the same issue. I can run souporcell to completion without a common_variants file, but when I add that, it crashes at the doublet detection step with the same error as @MrLocuace , and a very similar warning about KI270728.1, albeit at a different site:

```
inconsistent naming convention for record:
KI270728.1	1035268	1035271
```

```
sorting retagged bam files
merging sorted bams
cleaning up tmp samfiles
using common variants
8
running vartrix
running souporcell clustering
/opt/souporcell/souporcell/target/release/souporcell -k 3 -a /path/to/out/ref.mtx --restarts 100 -b /path/to/cell_barcodes.tsv --min_ref 10 --min_alt 10 --threads 8
running souporcell doublet detection

***** WARNING: File /path/to/out/depth_merged.bed has inconsistent naming convention for record:
KI270728.1	1035268	1035271

***** WARNING: File /path/to/out/SAM24434292/depth_merged.bed has inconsistent naming convention for record:
KI270728.1	1035268	1035271

Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 596, in <module>
    doublets(args, ref_mtx, alt_mtx, cluster_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 541, in doublets
    subprocess.check_call([directory+"/troublet/target/release/troublet", "--alts", alt_mtx, "--refs", ref_mtx, "--clusters", cluster_file], stdout = dub, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/souporcell/troublet/target/release/troublet', '--alts', '/path/to/out/alt.mtx', '--refs', '/path/to/out/ref.mtx', '--clusters', '/path/to/out/clusters_tmp.tsv']' returned non-zero exit status 101.
```

I also notived that:
- the `comon_variants_covered.vcf` only has the metadata headers, then is empty.
- both `ref.mtx` and `alt.mtx` are empty
- `clusters.tmp` is empty, but clusters_tmp.tsv` has the same values for all barcodes, eg:
```
TCATGCCTCCACTTTA-1	0	-1.0986123	-1.0986123	-1.0986123
GAACTGTCACATCCCT-1	0	-1.0986123	-1.0986123	-1.0986123
TGTGCGGTCTCCAAGA-1	0	-1.0986123	-1.0986123	-1.0986123
TATCAGGAGCATATGA-1	0	-1.0986123	-1.0986123	-1.0986123
CTCCTTTCAGTACTAC-1	0	-1.0986123	-1.0986123	-1.0986123
```

I don't know if this could be to inconsistent naming between the reference gneome fasta and the common variants VCF.
I'm using [GRCh38 2020-A provided by 10x](https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build) and the common variants file for GRCh38 provided in the souporcell docs.

When I check the contig names for the fasta, this is the naming schema, and there are several contigs not in the VCF:
```
>chr1 1
>chr10 10
>chr11 11
>chr12 12
>chr13 13
>chr14 14
>chr15 15
>chr16 16
>chr17 17
>chr18 18
>chr19 19
>chr2 2
>chr20 20
>chr21 21
>chr22 22
>chr3 3
>chr4 4
>chr5 5
>chr6 6
>chr7 7
>chr8 8
>chr9 9
>chrM MT
>chrX X
>chrY Y
>KI270728.1 KI270728.1
>KI270727.1 KI270727.1
>KI270442.1 KI270442.1
>KI270729.1 KI270729.1
>GL000225.1 GL000225.1
>KI270743.1 KI270743.1
>GL000008.2 GL000008.2
>GL000009.2 GL000009.2
.
.
.
[many KIXXXXX.X and GLOXXXXX.X contigs]
.
.
>KI270394.1 KI270394.1
```

and this for the VCF:

```
##fileDate=05122018_15h52m43s
##source=IGSRpipeline
##reference=ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa

##contig=<ID=chr1>
##contig=<ID=chr2>
##contig=<ID=chr3>
##contig=<ID=chr4>
##contig=<ID=chr5>
##contig=<ID=chr6>
##contig=<ID=chr7>
##contig=<ID=chr8>
##contig=<ID=chr9>
##contig=<ID=chr10>
##contig=<ID=chr11>
##contig=<ID=chr12>
##contig=<ID=chr13>
##contig=<ID=chr14>
##contig=<ID=chr15>
##contig=<ID=chr16>
##contig=<ID=chr17>
##contig=<ID=chr18>
##contig=<ID=chr19>
##contig=<ID=chr20>
##contig=<ID=chr21>
##contig=<ID=chr22>
##contig=<ID=chrX>

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1      16103   .       T       G       .       PASS    AF=0.02;AC=126;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.04;AFR_AF=0.03
```

Note all the KLIXXXX.X and GLOXXXX.X contigs in the reference, and not in the VCF.

Also, do the contig IDs in the VCF metadata, ie `contig=<ID=chr22` match the names in the fasta `>chr2 2` as required?

In the actual data of the VCF (not the headers), it's just the chromosome number under `#CHROM `, ie `22`, instead of `chr22`. Could this be the problem?

**Comment by wheaton5** [comment]
Yeah, there is a naming schema mismatch from the vcf (actual data not header) being 1,2,etc vs chr1,chr2,etc

that will cause empty data which seems to only actually error in doublet detection. I should add a check for this

**Comment by carmensandoval** [comment]
So I modified the vcf to use chr1, chr2, chr3, etc in CHROM to match the fasta contig ids, and unfortunately I'm still getting the same error:

Showing only othe first row for each chr:
```
> awk '!seen[$1]++ || /^#/' common_variants_grch38_chr.vcf

##fileformat=VCFv4.3
##fileDate=05122018_15h52m43s
##source=IGSRpipeline
##reference=ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1)">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=EAS_AF,Number=A,Type=Float,Description="Allele frequency in the EAS populations calculated from AC and AN, in the range (0,1)">
##INFO=<ID=EUR_AF,Number=A,Type=Float,Description="Allele frequency in the EUR populations calculated from AC and AN, in the range (0,1)">
##INFO=<ID=AFR_AF,Number=A,Type=Float,Description="Allele frequency in the AFR populations calculated from AC and AN, in the range (0,1)">
##INFO=<ID=AMR_AF,Number=A,Type=Float,Description="Allele frequency in the AMR populations calculated from AC and AN, in the range (0,1)">
##INFO=<ID=SAS_AF,Number=A,Type=Float,Description="Allele frequency in the SAS populations calculated from AC and AN, in the range (0,1)">
##INFO=<ID=VT,Number=.,Type=String,Description="indicates what type of variant the line represents">
##INFO=<ID=EX_TARGET,Number=0,Type=Flag,Description="indicates whether a variant is within the exon pull down target boundaries">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr1>
##contig=<ID=chr2>
##contig=<ID=chr3>
##contig=<ID=chr4>
##contig=<ID=chr5>
##contig=<ID=chr6>
##contig=<ID=chr7>
##contig=<ID=chr8>
##contig=<ID=chr9>
##contig=<ID=chr10>
##contig=<ID=chr11>
##contig=<ID=chr12>
##contig=<ID=chr13>
##contig=<ID=chr14>
##contig=<ID=chr15>
##contig=<ID=chr16>
##contig=<ID=chr17>
##contig=<ID=chr18>
##contig=<ID=chr19>
##contig=<ID=chr20>
##contig=<ID=chr21>
##contig=<ID=chr22>
##contig=<ID=chrX>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr1    16103   .       T       G       .       PASS    AF=0.02;AC=126;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.04;AFR_AF=0.03;AMR_AF=0.03;SAS_AF=0.02;VT=SNP;DP=29994
chr2    10560   .       G       A       .       PASS    AF=0.05;AC=252;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.02;AFR_AF=0.13;AMR_AF=0.04;SAS_AF=0.02;VT=SNP;DP=6665
chr3    11805   .       T       A       .       PASS    AF=0.02;AC=89;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.01;AFR_AF=0.01;AMR_AF=0.01;SAS_AF=0.05;VT=SNP;DP=10529
chr4    10208   .       G       A       .       PASS    AF=0.06;AC=315;NS=2548;AN=5096;EAS_AF=0.03;EUR_AF=0.03;AFR_AF=0.11;AMR_AF=0.05;SAS_AF=0.06;VT=SNP;DP=14466
chr5    11875   .       G       A       .       PASS    AF=0.05;AC=267;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.01;AFR_AF=0.17;AMR_AF=0.02;SAS_AF=0.02;VT=SNP;DP=1908
chr6    121495  .       C       T       .       PASS    AF=0.06;AC=305;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.03;AFR_AF=0.18;AMR_AF=0.04;SAS_AF=0.0;VT=SNP;DP=14989
chr7    31439   .       T       A       .       PASS    AF=0.3;AC=1530;NS=2548;AN=5096;EAS_AF=0.25;EUR_AF=0.41;AFR_AF=0.08;AMR_AF=0.3;SAS_AF=0.52;VT=SNP;DP=29896
chr8    71179   .       A       G       .       PASS    AF=0.02;AC=127;NS=2548;AN=5096;EAS_AF=0.01;EUR_AF=0.0;AFR_AF=0.07;AMR_AF=0.01;SAS_AF=0.01;VT=SNP;DP=8037
chr9    10648   .       G       A       .       PASS    AF=0.08;AC=388;NS=2548;AN=5096;EAS_AF=0.07;EUR_AF=0.06;AFR_AF=0.08;AMR_AF=0.08;SAS_AF=0.08;VT=SNP;DP=20978
chr10   11501   .       C       A       .       PASS    AF=0.05;AC=267;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.05;AFR_AF=0.07;AMR_AF=0.03;SAS_AF=0.1;VT=SNP;DP=20462
chr11   128446  .       G       A       .       PASS    AF=0.04;AC=182;NS=2548;AN=5096;EAS_AF=0.01;EUR_AF=0.04;AFR_AF=0.0;AMR_AF=0.02;SAS_AF=0.12;VT=SNP;DP=12895
chr12   10709   .       G       A       .       PASS    AF=0.15;AC=760;NS=2548;AN=5096;EAS_AF=0.15;EUR_AF=0.16;AFR_AF=0.09;AMR_AF=0.19;SAS_AF=0.19;VT=SNP;DP=6811
chr13   18171494        .       A       G       .       PASS    AF=0.09;AC=454;NS=2548;AN=5096;EAS_AF=0.1;EUR_AF=0.13;AFR_AF=0.07;AMR_AF=0.11;SAS_AF=0.05;VT=SNP;DP=351976
chr14   16038675        .       C       T       .       PASS    AF=0.04;AC=227;NS=2548;AN=5096;EAS_AF=0.06;EUR_AF=0.02;AFR_AF=0.01;AMR_AF=0.1;SAS_AF=0.06;VT=SNP;DP=9775
chr15   17009590        .       G       T       .       PASS    AF=0.32;AC=1620;NS=2548;AN=5096;EAS_AF=0.3;EUR_AF=0.44;AFR_AF=0.11;AMR_AF=0.4;SAS_AF=0.43;VT=SNP;DP=19785
chr16   10031   .       T       C       .       PASS    AF=0.03;AC=156;NS=2548;AN=5096;EAS_AF=0.02;EUR_AF=0.01;AFR_AF=0.06;AMR_AF=0.02;SAS_AF=0.03;VT=SNP;DP=4237
chr17   121314  .       G       C       .       PASS    AF=0.06;AC=308;NS=2548;AN=5096;EAS_AF=0.07;EUR_AF=0.05;AFR_AF=0.07;AMR_AF=0.05;SAS_AF=0.05;VT=SNP;DP=476
chr18   36427   .       G       A       .       PASS    AF=0.3;AC=1545;NS=2548;AN=5096;EAS_AF=0.35;EUR_AF=0.22;AFR_AF=0.31;AMR_AF=0.28;SAS_AF=0.35;VT=SNP;DP=25309
chr19   91015   .       T       C       .       PASS    AF=0.03;AC=156;NS=2548;AN=5096;EAS_AF=0.01;EUR_AF=0.03;AFR_AF=0.05;AMR_AF=0.02;SAS_AF=0.04;VT=SNP;DP=38513
chr20   61818   .       C       T       .       PASS    AF=0.02;AC=78;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.0;AFR_AF=0.06;AMR_AF=0.0;SAS_AF=0.0;VT=SNP;DP=97707
chr21   5033884 .       G       A       .       PASS    AF=0.1;AC=489;NS=2548;AN=5096;EAS_AF=0.02;EUR_AF=0.0;AFR_AF=0.22;AMR_AF=0.02;SAS_AF=0.16;VT=SNP;DP=6818
chr22   10516173        .       A       G       .       PASS    AF=0.02;AC=121;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.02;AFR_AF=0.05;AMR_AF=0.02;SAS_AF=0.0;VT=SNP;DP=8203
chrX    12568   .       C       T       .       PASS    AF=0.02;AC=98;NS=2548;AN=5096;EAS_AF=0.0;EUR_AF=0.0;AFR_AF=0.07;AMR_AF=0.01;SAS_AF=0.0;VT=SNP;DP=8617
```

This now matches the fasta ids, but the error is still the same, and the `ref.mtx` and `var.mtx` appear empty.

There are still all those contigs in the reference that are not in the VCF, but all the chromosomes in common between the two have the same names.

Do you think maybe I should remove those extra contigs (including chrY and chrM) from the fasta?

**Comment by wheaton5** [comment]
If you run with the same output directory name without deleting the previous directory, it tries to use the partially completed steps. And in this case, those are empty. So delete output directory and try again.

**Comment by carmensandoval** [comment]
I am actively deleting the output files produced after remapping and retagging with every attempt, so these empty .mtx files are new.

Unless I have to remap and retag as well with the updated vcf, but I don't think that file plays into the workflow until after remapping and retagging?

**Comment by wheaton5** [comment]
Its the .done files that matter

**Comment by wheaton5** [comment]
make sure that the fasta, bam, and vcf all have the same naming convention. But also just rerun with a different output directory name just in case. You can actually skip realignment when using common_variants. But then you have to make sure the original bam has the same naming convention.
