### ISSUE TITLE
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'

### ISSUE THREAD

**Issue by rdf1993** [wheaton5/souporcell#177]
I am writing to seek your help regarding an error I am encountering with your Souporcell pipeline. After singularity pull shub://wheaton5/souporcell, I get the souporcell_latest.sif file,  but it couldn't work 

singularity exec /mnt/volume3/00_biosoft/singularity_image/souporcell_latest.sif souporcell_pipeline.py -i gex_possorted_bam.bam --cell_tag CR -b barcodes.tsv -f Homo_sapiens.GRCh38.dna.primary_assembly_addchr.fa -t 16 -o ./05.souporcell/GEX/ -k 2
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/envs/py36/lib/python3.6/site.py", line 545, in <module>
    main()
  File "/usr/local/envs/py36/lib/python3.6/site.py", line 531, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/local/envs/py36/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/local/envs/py36/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/local/envs/py36/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/local/envs/py36/lib/python3.6/sysconfig.py", line 609, in get_config_var
    return get_config_vars().get(name)
  File "/usr/local/envs/py36/lib/python3.6/sysconfig.py", line 558, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/local/envs/py36/lib/python3.6/sysconfig.py", line 429, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'
(base) ➜  volume3 pip install _sysconfigdata_x86_64_conda_cos7_linux_gnu
ERROR: Invalid requirement: '_sysconfigdata_x86_64_conda_cos7_linux_gnu'

**Comment by wheaton5** [comment]
I have not seen this before. But it seems unlikely to be in souporcell itself. But singularity should handle this… id try upgrading singularity and retrying (delete the output directory for the souporcell run).

**Comment by rdf1993** [comment]
I used another conda env, this problem had been solved. But something is strange that it can't find the barcode.tsv files. 

singularity exec /mnt/volume3/rdf/00_biosoft/singularity_image/souporcell_latest.sif souporcell_pipeline.py -i /mnt/volume3/rdf/outs/gex_possorted_bam.bam --cell_tag CR -b /mnt/volume3/rdf/outs/barcodes.tsv -f /mnt/volume3/rdf/01_refData/GRCh38_fa/Homo_sapiens.GRCh38.dna.primary_assembly_addchr.fa -t 16 -o /mnt/volume3/rdf/LARRY/LARRY_hESCs/LARRY_primed_H1H9/barcode_calling/05.souporcell/GEX/ -k 2
checking modules
imports done
checking bam for expected tags
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 64, in <module>
    with open_function(args.barcodes) as barcodes:
  File "/opt/souporcell/souporcell_pipeline.py", line 57, in <lambda>
    open_function = lambda f: gzip.open(f,"rt") if f[-3:] == ".gz" else open(f)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/volume3/rdf/LARRY/LARRY_hESCs/LARRY_primed_H1H9/outs/barcodes.tsv'
(sc_py) ➜  volume3 cat /mnt/volume3/rdf/outs/barcodes.tsv | head
AAACAGCCAAGGTCGA
AAACAGCCACCCACAG
AAACAGCCACGTTACA
AAACAGCCACTCAACA
AAACAGCCAGGAAGCC
AAACAGCCATAATCGT
AAACAGCCATAGCTTG
AAACAGCCATGTTGCA
AAACATGCAACCCTAA
AAACATGCAATTAACC

**Comment by rdf1993** [comment]
I used another conda env, this problem had been solved. But something is strange that it can't find the barcode.tsv files.

singularity exec /mnt/volume3/rdf/00_biosoft/singularity_image/souporcell_latest.sif souporcell_pipeline.py -i /mnt/volume3/rdf/outs/gex_possorted_bam.bam --cell_tag CR -b /mnt/volume3/rdf/outs/barcodes.tsv -f /mnt/volume3/rdf/01_refData/GRCh38_fa/Homo_sapiens.GRCh38.dna.primary_assembly_addchr.fa -t 16 -o /mnt/volume3/rdf/LARRY/LARRY_hESCs/LARRY_primed_H1H9/barcode_calling/05.souporcell/GEX/ -k 2
checking modules
imports done
checking bam for expected tags
Traceback (most recent call last):
File "/opt/souporcell/souporcell_pipeline.py", line 64, in
with open_function(args.barcodes) as barcodes:
File "/opt/souporcell/souporcell_pipeline.py", line 57, in
open_function = lambda f: gzip.open(f,"rt") if f[-3:] == ".gz" else open(f)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/volume3/rdf/outs/barcodes.tsv'
(sc_py) ➜ volume3 cat /mnt/volume3/rdf/outs/barcodes.tsv | head
AAACAGCCAAGGTCGA
AAACAGCCACCCACAG
AAACAGCCACGTTACA
AAACAGCCACTCAACA
AAACAGCCAGGAAGCC
AAACAGCCATAATCGT
AAACAGCCATAGCTTG
AAACAGCCATGTTGCA
AAACATGCAACCCTAA
AAACATGCAATTAACC

**Comment by wheaton5** [comment]
There is a way u can bind directories in singularity. I would try searching that

**Comment by rdf1993** [comment]
thanks, I will try to bind my volume to singularity
