### ISSUE TITLE
freebayes subprocess terminated error

### ISSUE THREAD

**Issue by Huimin721** [wheaton5/souporcell#225]
Dear author,

Thanks so much for developing the great tool. I recently applied it on a single nuclei data, and encountered some errors I have never met with 10x single cell data, here is the error:
Traceback (most recent call last):
  File "/hpcgotup/souporcell/souporcell_pipeline.py", line 584, in <module>
    final_vcf = freebayes(args, bam, fasta)
  File "/hpcgotup/souporcell/souporcell_pipeline.py", line 432, in freebayes
    assert not(procs[index].returncode), "freebayes subprocess terminated abnormally with code " + str(procs[index].returncode)
AssertionError: freebayes subprocess terminated abnormally with code -6

here is the line I ran:
python /hpcgotup/souporcell/souporcell_pipeline.py -i /hpcgotup/$VAR/outs/possorted_genome_bam.bam -b /hpcgotup/$VAR/outs/filtered_feature_bc_matrix/barcodes.tsv.gz -f /refdata/refdata-gex-GRCh38-2020-A/fasta/genome.fa -t 8 -o /hpcgotup/$VAR -k 2

Could you please advise on this? Thanks so much!

Best,
Huimin

**Comment by athuyvo** [comment]
I also ran into a similar error.

**Comment by baishahuang113-star** [comment]
I also ran into a same error.
