### ISSUE TITLE
Error running /opt/souporcell/consensus.py

### ISSUE THREAD

**Issue by fningtian** [wheaton5/souporcell#243]
I installed souporcell through singularity. When testing it on the demux_data, I ran into the error below. Could you kindly help look into this? 

Note that I am running souporcell on a remote server. 

merging vcfs
running vartrix
running souporcell clustering
/opt/souporcell/souporcell/target/release/souporcell -k 4 -a souporcell/demux_data_test/alt.mtx -r souporcell/demux_data_test/ref.mtx --restarts 100 -b souporcell/demux_data_test/GSM2560245_barcodes.tsv --min_ref 10 --min_alt 10 --threads 20
running souporcell doublet detection
running co inference of ambient RNA and cluster genotypes
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 600, in <module>
    consensus(args, ref_mtx, alt_mtx, doublet_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 549, in consensus
    subprocess.check_call([directory+"/consensus.py", "-c", doublet_file, "-a", alt_mtx, "-r", ref_mtx, "-p", args.ploidy,
  File "/miniconda3/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/souporcell/consensus.py', '-c', 'souporcell/demux_data_test/clusters.tsv', '-a', 'souporcell/demux_data_test/alt.mtx', '-r', 'souporcell/demux_data_test/ref.mtx', '-p', '2', '--output_dir', 'souporcell/demux_data_test', '--soup_out', 'souporcell/demux_data_test/ambient_rna.txt', '--vcf_out', 'souporcell/demux_data_test/cluster_genotypes.vcf', '--vcf', 'souporcell/demux_data_test/souporcell_merged_sorted_vcf.vcf.gz']' returned non-zero exit status 1.

Thanks!

**Comment by fningtian** [comment]
Thanks, Haynes.

The run was through singularity. 

I don't think I have consensus.err. Below are the files available in the output directory. clusters.tsv is there, and the most recent file is troublet.done. 

<img width="426" alt="Screenshot 2024-08-08 at 1 06 11 PM" src="https://github.com/user-attachments/assets/7ac7244c-018a-4a3e-b727-7267e1081174">

Thanks,
Funing

**Comment by wheaton5** [comment]
I ran this recently (yesterday lol) with the only difference being I was using a common variants file and skip_remap, but that should have nothing to do with your error. I just checked, and I don't write a consensus.err file (most steps I write stderr to an associated .err file) so the stderr should just be what you showed above. And there is basically nothing to go on. Let me think about the best way to proceed.

**Comment by wheaton5** [comment]
I uninstalled my local pystan, deleted all of the consensus outputs (the system is set up to run from partial output doing the steps without .done files), and reran and it worked. 

checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory output_dir_name2
running co inference of ambient RNA and cluster genotypes
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_ca32e407e94c33afe8f72cdc7357f09f NOW.
35901 excluded for potential RNA editing
120 doublets excluded from genotype and ambient RNA estimation
468 not used for soup calculation due to possible RNA edit
Initial log joint probability = -73775.1
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
       6      -19804.2    0.00133271      0.120065      0.9251      0.9251       21
Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance

I will try to recreate exactly your example, but I am a bit flummoxed and don't think that rerunning from scratch without common variants or skip remap should change anything about this final step. 

Lets see, maybe can you try the following
singularity exec souporcell.sif python
that will give you an interactive python terminal using the singularity container, then run
import pystan

Does that error?

**Comment by wheaton5** [comment]
all I can think is that pystan uses some optimizations that require certain nonstandard cpu operations and maybe that could error, but it should auto detect that stuff and fall back on the non-optimized x86 standard operations if the cpu doesn't have them.

**Comment by wheaton5** [comment]
you could also rerun just that step with

singularity exec souporcell.sif /opt/souporcell/consensus.py -c souporcell/demux_data_test/clusters.tsv -a souporcell/demux_data_test/alt.mtx -r souporcell/demux_data_test/ref.mtx -p 2 --output_dir souporcell/demux_data_test --soup_out souporcell/demux_data_test/ambient_rna.txt --vcf_out souporcell/demux_data_test/cluster_genotypes.vcf --vcf souporcell/demux_data_test/souporcell_merged_sorted_vcf.vcf.gz

and see if you get any more useful error output?

**Comment by fningtian** [comment]
Thank you so much for looking into this issue.

I tried singularity exec souporcell.sif python and then import pystan. This worked.

However, running the command below on the remote server gives an error. 
singularity exec souporcell.sif /opt/souporcell/consensus.py -c souporcell/demux_data_test/clusters.tsv -a souporcell/demux_data_test/alt.mtx -r souporcell/demux_data_test/ref.mtx -p 2 --output_dir souporcell/demux_data_test --soup_out souporcell/demux_data_test/ambient_rna.txt --vcf_out souporcell/demux_data_test/cluster_genotypes.vcf --vcf souporcell/demux_data_test/souporcell_merged_sorted_vcf.vcf.gz

Error message
<img width="644" alt="Screenshot 2024-08-08 at 2 48 05 PM" src="https://github.com/user-attachments/assets/032f3924-195a-427d-b2e6-9ad2f81b8dc5">

Additionally, I was wondering if there is a common_variants_grch38.vcf you could share. The one on GitHub does not seem to work. My email address: fning.tian@gmail.com

Thanks,
Funing

**Comment by wheaton5** [comment]
```
curl ftp://ftp.eng.auburn.edu/pub/whh0027/common_variants_grch38.vcf.gz -o common_variants_grch38.vcf.gz
```

**Comment by wheaton5** [comment]
im really at a loss for how to approach this error though. I can't recreate it on my system.

**Comment by wheaton5** [comment]
I have updated the common variants links in the readme though

**Comment by wheaton5** [comment]
What is OS and version is this server? With some googling, some people get this with container optimized servers

**Comment by wheaton5** [comment]
ah, it looks like $TMPDIR needs to be manually set??? Im not sure if I need to do that in singularity or if you need to do it on your server. try running export TMPDIR=/path/to/somewhere before running. Then if that doesn't work try 

singularity exec souporcell.sif export TMPDIR=/current/working/directory && /opt/souporcell/consensus.py -c souporcell/demux_data_test/clusters.tsv -a souporcell/demux_data_test/alt.mtx -r souporcell/demux_data_test/ref.mtx -p 2 --output_dir souporcell/demux_data_test --soup_out souporcell/demux_data_test/ambient_rna.txt --vcf_out souporcell/demux_data_test/cluster_genotypes.vcf --vcf souporcell/demux_data_test/souporcell_merged_sorted_vcf.vcf.gz

obv updating the paths for those directories as needed

**Comment by fningtian** [comment]
I reached out to the server. After making /scratch available in the container and setting TMPDIR to my scratch directory, it works.  See below. 

singularity exec --bind /scratch:/scratch --contain souporcell_release.sif /opt/souporcell/consensus.py

Thanks again for your help!

**Comment by wheaton5** [comment]
Wow. Im actually amazed we fixed that one. Ill remember this one for future use
