### ISSUE TITLE
Error with default pipeline

### ISSUE THREAD

**Issue by mxposed** [wheaton5/souporcell#29]
Hi, I ran into this problem:
```
Initial log joint probability = -137008
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes
Exception: log_mix: lambda1 is -nan, but must not be nan!  (in 'unknown file name' at line 73)

Error evaluating model log probability: Non-finite gradient.

       6      -68531.7   0.000733154     0.0164666           1           1       13
Optimization terminated normally:
  Convergence detected: relative gradient magnitude is below tolerance
/usr/local/envs/py36/lib/python3.6/site-packages/pystan/misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating
` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):
111306 excluded for potential RNA editing
444 doublets excluded from genotype and ambient RNA estimation
2717 not used for soup calculation due to possible RNA edit
Traceback (most recent call last):
  File "/opt/souporcell/consensus.py", line 433, in <module>
    with open("tempsouporcell.vcf") as tmp:
FileNotFoundError: [Errno 2] No such file or directory: 'tempsouporcell.vcf'
```
and then later
```
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 504, in <module>
    consensus(args, ref_mtx, alt_mtx, doublet_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 454, in consensus
    "--soup_out", args.out_dir + "/ambient_rna.txt", "--vcf_out", args.out_dir + "/cluster_genotypes.vcf", "--vcf", final_vcf])
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['consensus.py', '-c', '/data/genotype/SC76/clusters.tsv', '-a', '/data/genotype/SC76/alt.mtx', '-r', '/data/genotype/SC76/ref.mtx', '-p', '2', '--soup_out', '/data/genotype/SC76/ambient_rna.txt', '--vcf_out', '/data/genotype/SC76/cluster_genotypes.vcf', '--vcf', '/data/genotype/SC76/common_variants_covered.vcf']' returned non-zero exit status 1.
```

How to debug what went wrong? Other 10x samples I ran in parallel did ok
I was using the version of singularity image from the current README

**Comment by wheaton5** [comment]
I think I see the problem. Looks like it is creating a temp file in the directory souporcell is run from, not the output directory. So if you are running multiple in parallel they might step on each other's feet. I will fix and make another singularity container then post here again when that is done.

**Comment by mxposed** [comment]
Thank you. Meanwhile I'll rerun them from different directories

**Comment by wheaton5** [comment]
It is the very final step. The only things that that step affect are the ambient RNA estimation and the cluster genotype calls. So if you are just interested in the cell clustering and doublet detection, those should be unaffected and complete.

**Comment by wheaton5** [comment]
this is now fixed in current version
