### ISSUE TITLE
Vatrix error 

### ISSUE THREAD

**Issue by rich-green-aifimmunology** [wheaton5/souporcell#57]
I have been running souporcell and it runs great with out custom VCFs but now I want to link those clusters to known genotypes. I recently received WGS data and made merged a VCF with BCFTools for my 7 samples/clusters. The single cell data was produced in cell ranger using hg38 but the WGS data was made using hg19 so I use crossmap to convert the WGS coordinates back to hg38. When I now get to the vartrix step of the pipeline I receive the following error:

/apps/data/psomagen/bam_dir/10x# singularity exec /shared/apps/souporcell.sif souporcell_pipeline.py -i B001-RP1C1W2.bam -b  B001-RP1C1W2_barcodes.tsv  -f genome.fa -t 60 -o B001_RP1C1W2_SOC_results_w_genotype -k 7 --skip_remap True --known_genotypes merged_sorted.genome.crossmap.updated.vcf --known_genotypes_sample_names BR1001 BR1002 BR1003 CU1001 CU1002 CU1004 IMM19_383
checking modules
imports done
checking bam for expected tags
checking fasta
restarting pipeline in existing directory B001_RP1C1W2_SOC_results_w_genotype
running vartrix
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 556, in <module>
    vartrix(args, final_vcf, bam)
  File "/opt/souporcell/souporcell_pipeline.py", line 481, in vartrix
    subprocess.check_call(cmd, stdout = out, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vartrix', '--mapq', '30', '-b', 'B001-RP1C1W2.bam', '-c', 'B001-RP1C1W2_barcodes.tsv', '--scoring-method', 'coverage', '--threads', '60', '--ref-matrix', 'B001_RP1C1W2_SOC_results_w_genotype/ref.mtx', '--out-matrix', 'B001_RP1C1W2_SOC_results_w_genotype/alt.mtx', '-v', 'B001_RP1C1W2_SOC_results_w_genotype/common_variants_covered.vcf', '--fasta', 'genome.fa', '--umi']' died with <Signals.SIGKILL: 9>.

When I look at the vartrix.err file it says:
/apps/data/psomagen/bam_dir/10x# cat B001_RP1C1W2_SOC_results_w_genotype/vartrix.err
[W::vcf_parse] Contig 'MT' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '21' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig '9' is not defined in the header. (Quick workaround: index the file with tabix.)
 and so on

I did make a tabix index when it was a vcf.gz but am unable to make an index in tabix (or BCFtools) on an uncompressed vcf. The indexes I made are present in the directory:

ls  merged_sorted.genomes.crossmap.updated.vcf.* | sort
merged_sorted.genomes.crossmap.updated.vcf.gz
merged_sorted.genomes.crossmap.updated.vcf.gz.gzi
merged_sorted.genomes.crossmap.updated.vcf.gzi
merged_sorted.genomes.crossmap.updated.vcf.gz.tbi

Please let me know what I can do to resolve this VCF issue within souporcell so I can easily match these clusters back to their genotype. Thank you so much for your help
-Rich

**Comment by wheaton5** [comment]
Well, that vartrix.err output are warnings, not errors. But then it panics. Generally this happens when vartrix tries to seek to a location that isn't in the bam. Are you certain your vcf and fasta have consistent chromosome names (chr1 vs 1 for instance, but also make sure this is consistent for MT and any extra contigs like hap alts or the decoy contig). I've made this mistake countless times and I think that is where it fails. Then the other thing you can do is to just remap the WGS data to the genome the cellranger run used and recall variants and merge them. I assume its not the coordinate liftover that is the problem, but I generally don't trust those things.

**Comment by rich-green-aifimmunology** [comment]
Thanks. I made sure the VCF and genome.fa were consistent. Do they need to be in the same order?

**Comment by rich-green-aifimmunology** [comment]
Here are the first few lines of the fasta and first few contigs in the header of VCF
Fasta
>1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
>10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF
>11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF

##contig=<ID=1,length=248956422,assembly=genome.fa>
##contig=<ID=10,length=133797422,assembly=genome.fa>
##contig=<ID=11,length=135086622,assembly=genome.fa>

**Comment by wheaton5** [comment]
Can you also make sure this is consistent with the bam?

Hmm.. Another potential here is that if the fasta file was indexed previously, depending on what program is used to index it, the index file could see the first chromosome name as "1" or "1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF". You can check this by opening up the genome.fa.fai file. If the names are the latter, you can delete that file and run the following in python
```
import pyfasta
pyfasta.Fasta('genome.fa', key_fn=lambda key: key.split()[0])
```
Do they need to be in the same order? I'm really not sure. I think so.

**Comment by wheaton5** [comment]
Also for the vcf, it doesnt really matter what is in the header, it matters what is in the records. It could say 1 in the header and chr1 in the records depending on which program you used to liftover.

**Comment by wheaton5** [comment]
Also is there any more info in the vartrix.err file? Look down to the bottom.

**Comment by rich-green-aifimmunology** [comment]
Nope . no additional info. Remapping WGS to hg38 now. will retry afterwards

**Comment by rich-green-aifimmunology** [comment]
singularity exec /shared/apps/souporcell.sif souporcell_pipeline.py -i B001-RP1C1W2.bam -b  B001-RP1C1W2_barcodes.tsv -f genome.fa -t 60 -k 5 -o B001_RP1C1W2_SOC_results_genotype --known_genotypes all_sorted_genome.nochr.g5mac3.vcf.recode.vcf --known_genotypes_sample_names BR1001 BR1002 BR1003 CU1001 CU1004


I trimmed my vcf down but now receive a new error (below)

(base) root@green-ide:/apps/data/psomagen/bam_dir/10x/B001_RP1C1W2_SOC_results_genotype# cat clusters.err
total loci used 89824
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32thread '
<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:329:32
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', thread 'src/main.rs<unnamed>:' panicked at '329called `Option::unwrap()` on a `None` value:', 32src/main.rs
:329:32thread '

**Comment by wheaton5** [comment]
Sorry this fell off my radar.

Can you make sure all of your vcf records have the GT field?

**Comment by rich-green-aifimmunology** [comment]
No problem Wheaton. I was previously running into some memory issues during the vartrix step (lots of snps) but Im using the newer version of vartrix now and I believe that Is resolved.

I just wanted some conceptual verification. While running soup or cell, If I provide a cell ranger bam file that contains multi-individual, cell hashed barcoded data and my genotype vcf that contains a merged vcf encompassing the same group of individuals’ variant information will souporcell be able to distinguish and annotate the single cell populations by genotype using their variants? I noticed there is an option for genotype names to be provided with a merged vcf.

Please let me know.
Thanks
-Rich

On Sep 4, 2020, at 2:49 PM, Haynes Heaton <notifications@github.com> wrote:

﻿

Sorry this fell off my radar.

Can you make sure all of your vcf records have the GT field?

**Comment by wheaton5** [comment]
Right now how known_genotypes works it requires known_genotypes_sample_names. The reason for this kind of silly in the way my vcf parser gives me the sample names (as a set, not a list, so unordered). So the easy workaround was to require the user to provide the sample names and then i use that order going forward. I hope this helps. Let me know.
Best,
Haynes

**Comment by rich-green-aifimmunology** [comment]
Great to confirm if I provide the merged vcf and the genotype names parameter it annotate by genotype name and not cluster. Do I have that correct? It doesn’t cover this in the paper. Seems like a newer feature post manuscript.
Thanks
-Rich

On Sep 10, 2020, at 8:52 AM, Haynes Heaton <notifications@github.com> wrote:

﻿

Right now how known_genotypes works it requires known_genotypes_sample_names. The reason for this kind of silly in the way my vcf parser gives me the sample names (as a set, not a list, so unordered). So the easy workaround was to require the user to provide the sample names and then i use that order going forward. I hope this helps. Let me know.
Best,
Haynes

**Comment by wheaton5** [comment]
Actually this is something I need to fix. It still annotates by cluster, but the clusters are in the same order as the sample names given

So if you give --known_genotypes_sample_names foo bar
then cluster 0 will refer to sample foo and cluster 1 will refer to cluster bar.

It is on my list of things to fix.

Best,
Haynes

**Comment by rich-green-aifimmunology** [comment]
Ok thanks for letting me know. Do you know when your estimated ETA is to fix this? I think it will be very powerful to allow it the ability to annotate by cluster based of multiple, merged VCFs.
Thanks Haynes
-Rich

On Sep 10, 2020, at 9:47 AM, Haynes Heaton <notifications@github.com> wrote:

﻿

Actually this is something I need to fix. It still annotates by cluster, but the clusters are in the same order as the sample names given

So if you give --known_genotypes_sample_names foo bar
then cluster 0 will refer to sample foo and cluster 1 will refer to cluster bar.

It is on my list of things to fix.

Best,
Haynes
