### ISSUE TITLE
Soupoercell Error

### ISSUE THREAD

**Issue by KASHISH72** [wheaton5/souporcell#59]
Hello,

I am trying to run souorcell and getting this error. Can you tell me if you have fixed this.

sorting retagged bam files
merging sorted bams
cleaning up tmp samfiles
running freebayes
Traceback (most recent call last):
  File "/usr/local/souporcell/1.0.0/souporcell_pipeline.py", line 555, in <module>
    final_vcf = freebayes(args, bam, fasta)
  File "/usr/local/souporcell/1.0.0/souporcell_pipeline.py", line 414, in freebayes
    assert not(procs[index].returncode), "freebayes subprocess terminated abnormally with code " + str(procs[index].returncode)
AssertionError: freebayes subprocess terminated abnormally with code 1

**Comment by wheaton5** [comment]
Going to need more info, but first. Is there are reason you couldn't use the singularity build? And if you are asking me if I have fixed it, does that mean you are working off an old version of souporcell?

What is your command?
There should be some .err files in the output directory which may give more info on this. Can you look for them and post anything relevant?

Thanks,
Haynes

**Comment by KASHISH72** [comment]
I am running this on cluster. I got the new version installed on out cluster and I was looking at previous issues and saw the same and that's why I asked if it is fixed.

Here is the error from the vcf file

freebayes: unrecognized option '--skip-coverage'
did you mean --min-coverage ?
freebayes -f /data/salomonis2/Genomes/Grch38-10X/GRCh38/fasta/genome.fa -iXu -C 2 -q 20 -n 3 -E 1 -m 30 --min-coverage 44 --pooled-continuous --skip-coverage 100000 -r 1:0-248956422 /data/salomonis2/External-Collaborations/Bone-marrow-UCSF/CellRanger/Demuxlet/BM_MNC_1_souporcell_0/souporcell_minimap_tagged_sorted.bam

**Comment by wheaton5** [comment]
freebayes options have changed over time. The version I use in the singularity build is 1.3.1 which you can see from the singularity.def file (singularity build definition file). It isn't broken so I haven't fixed it. Plenty of people are using souporcell regularly without this error. It's a version compatibility issue which is difficult to manage continuously unless you package everything together which is why containers such as singularity exist.
