### ISSUE TITLE
Stopped during remapping

### ISSUE THREAD

**Issue by achamess** [wheaton5/souporcell#8]
Hi again,
I used the new DL of souporcell from the README page.
This is what happened. Not sure what's going on.
Can I restart from what's already been done?
I used the script. Here is my input command:

```singularity exec souporcell.sif souporcell_pipeline.py \
-i /home/ec2-user/data/hSC_count/hSC_count/outs/possorted_genome_bam.bam \
-b /home/ec2-user/data/hSC_count/hSC_count/outs/filtered_feature_bc_matrix/barcodes.tsv \
-f /home/ec2-user/data/GRCh38-3.0.0_premrna/fasta/genome.fa \
-t 16 -o souporcell_k2 \
-k 2
```
and the output

```
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/py36/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
imports done
checking bam for expected tags
checking fasta
creating chunks
generating fastqs with cell barcodes and umis in readname
remapping with minimap2
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 424, in <module>
    minimap_tmp_files = remap(args, region_fastqs, all_fastqs)
  File "/opt/souporcell/souporcell_pipeline.py", line 162, in remap
    stdout = samfile, stderr = minierr)
  File "/opt/conda/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['minimap2', '-ax', 'splice', '-t', '16', '-G50k', '-k', '21', '-w', '11', '--sr', '-A2', '-B8', '-O12,32', '-E2,1', '-r200', '-p.5', '-N20', '-f1000,5000', '-n2', '-m20', '-s40', '-g2000', '-2K50m', '--secondary=no', '/home/ec2-user/data/GRCh38-3.0.0_premrna/fasta/genome.fa', 'souporcell_k2/tmp.fq']' died with <Signals.SIGKILL: 9>.
```

**Comment by wheaton5** [comment]
You will be able to restart from where you left off. But there is probably a problem with an updated minimap2 changing the command line options. So I will need to look into it and make a new container. For the future I will grab a specific release instead of grabbing master.

**Comment by wheaton5** [comment]
There should be a minimap.err file in the output directory. Does that say anything?

**Comment by wheaton5** [comment]
Oh this is sigkill 9. So it looks like it got terminated by an external entity. Are you running this on a cluster? How much memory did you request? minimap2 takes like 20-24Gb to build its index for human (I should host a version with the index already created...)

**Comment by achamess** [comment]
Hi @wheaton5 
Thanks so much for the quick reply. I'm running on AWS, so it shouldn't have gotten booted unless i need to change my memory limits. I'll get back to you with the minimap.err.

**Comment by achamess** [comment]
Just wanted to let you know the latest release carried to completion for me. Not sure what's different. I did it on my university cluster this time. Didn't run out of memory or space.

**Comment by XiaofeiSunUCSF** [comment]
I got the same error
Here is the one from 

> 55ffdfe56000-55ffdfe80000 r-xp 00000000 07:00 25597                      /opt/minimap2-2.7/minimap2
55ffe007f000-55ffe0080000 r--p 00029000 07:00 25597                      /opt/minimap2-2.7/minimap2
55ffe0080000-55ffe0081000 rw-p 0002a000 07:00 25597                      /opt/minimap2-2.7/minimap2
55ffe0f3f000-55ffe0fe6000 rw-p 00000000 00:00 0                          [heap]
7ffea82f3000-7ffea8315000 rw-p 00000000 00:00 0                          [stack]
7ffea8321000-7ffea8323000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
mapping
minimap2 -ax splice -t 32 -G50k -k 21 -w 11 --sr -A2 -B8 -O12,32 -E2,1 -r200 -p.5 -N20 -f1000,5000 -n2 -m20 -s40 -g2000 -2K50m --secondary=no /




[M::mm_idx_gen::76.729*1.54] collected minimizers
[M::mm_idx_gen::88.079*2.39] sorted minimizers
[M::main::88.080*2.39] loaded/built the index for 194 target sequence(s)
[M::mm_mapopt_update::88.080*2.39] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 194
[M::mm_idx_stat::94.835*2.29] distinct minimizers: 381286575 (95.43% are singletons); average occurrences: 1.291; average spacing: 6.295
*** Error in `minimap2': free(): invalid pointer: 0x00002b9ee34e5410 ***
