### ISSUE TITLE
Doublet calling takes up all memory then crashes

### ISSUE THREAD

**Issue by MarijnBerg** [wheaton5/souporcell#93]
Hi, I've been having some issues running SoupOrCell on our data.

It seems to have worked now up until the point where the doublet and ambient RNA detection is being done, at which point it takes about a minute to claim all of the 64GB of memory and promptly gets killed for doing so.

Here's the command used:

```
singularity exec souporcell.sif souporcell_pipeline.py \
-i '/home/marijn/Storage_2/MC_data/outs/possorted_genome_bam.bam' \
-b '/home/marijn/Storage_2/MC_data/outs/filtered_feature_bc_matrix/barcodes.tsv' \
-f '/home/marijn/References/refdata-cellranger-GRCh38-3.0.0/fasta/genome.fa' \
-t 16 \
-o '/home/marijn/Storage_2/SOC_out3' \
-k 40
```

An the error message:

```
running souporcell doublet detection
Traceback (most recent call last):
  File "/opt/souporcell/souporcell_pipeline.py", line 595, in <module>
    doublets(args, ref_mtx, alt_mtx, cluster_file)
  File "/opt/souporcell/souporcell_pipeline.py", line 540, in doublets
    subprocess.check_call([directory+"/troublet/target/release/troublet", "--alts", alt_mtx, "--refs", ref_mtx, "--clusters", cluster_file], stdout = dub, stderr = err)
  File "/usr/local/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/souporcell/troublet/target/release/troublet', '--alts', '/home/marijn/Storage_2/SOC_out3/alt.mtx', '--refs', '/home/marijn/Storage_2/SOC_out3/ref.mtx', '--clusters', '/home/marijn/Storage_2/SOC_out3/clusters_tmp.tsv']' died with <Signals.SIGKILL: 9>.
```
Any idea on why that's happening and how I can proceed anyway?
Or a way to skip the step? I'm really not that interested in the doublets or ambient RNA.

**Comment by MarijnBerg** [comment]
Got a tip from some coworkers to split it up into the individual 10X lanes so there are fewer samples as that might be the issue. Trying that now.
